# name: Publish image
# 
# on:
#   push:
#     branches: [ main ]
# 
# jobs:
#   release-main-test-docker-image:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           pull: true
#           push: true
#           tags: ${{ vars.DOCKER_IMAGE_REPOSITORY }}:${{ vars.DOCKER_IMAGE_MAIN_STAGE }}
#           target: ${{ vars.DOCKER_IMAGE_MAIN_STAGE }}